os:
  editPreset: "nvim"

keybinding:
  files:
    commitChanges: <c-c>

customCommands:
  - key: "c"
    context: "files"
    description: "commit files with format"
    prompts:
      - type: "menu"
        title: "What kind of commit type is it?"
        key: "Type"
        options:
          - name: "fix"
            description: "バグや不具合の修正"
            value: "fix"
          - name: "feat"
            description: "新機能の追加"
            value: "feat"
          - name: "docs"
            description: "ドキュメントの更新や改善"
            value: "docs"
          - name: "style"
            description: "コードフォーマットの修正、UIのみの変更"
            value: "style"
          - name: "refactor"
            description: "パフォーマンスの改善なしのコードの改善"
            value: "refactor"
          - name: "test"
            description: "テストの追加や改善"
            value: "test"
          - name: "perf"
            description: "パフォーマンスの改善"
            value: "perf"
          - name: "chore"
            description: "ビルドプロセスの変更や改善"
            value: "chore"
          - name: "wip"
            description: "作業中"
            value: "wip"
      - type: "input"
        title: "Enter the Message"
        key: "Message"
        initialValue: ""
      - type: "confirm"
        title: "Commit"
        body: "Commit with the message '{{.Form.Type}}: {{.Form.Message}}'. Is this okay?"
    command: "bash -c 'type=\"{{.Form.Type}}\"; message=\"{{.Form.Message}}\"; commit_message=\"$type: $message\"; git commit -m \"commit_message\"'"
