os:
  editPreset: "nvim"

keybinding:
  files:
    commitChanges: <c-c>

customCommands:
  - key: "c"
    context: "files"
    description: "commit files with format"
    prompts:
      - type: "menu"
        title: "What kind of commit type is it?"
        key: "Type"
        options:
          - name: "fix"
            description: "バグや不具合の修正"
            value: "fix"
          - name: "feat"
            description: "新機能の追加"
            value: "feat"
          - name: "docs"
            description: "ドキュメントの更新や改善"
            value: "docs"
          - name: "style"
            description: "コードのフォーマットの変更(セミコロンの追加や改行の修正など)"
            value: "style"
          - name: "refactor"
            description: "パフォーマンスの改善なしのコードの可読性の改善"
            value: "refactor"
          - name: "test"
            description: "テストの追加や改善"
            value: "test"
          - name: "perf"
            description: "パフォーマンスの改善"
            value: "perf"
          - name: "build"
            description: "ビルドプロセスの変更または依存関係のアップデート"
            value: "build"
          - name: "ci"
            description: "CI/CDの設定変更"
            value: "ci"
          - name: "chore"
            description: "その他の変更"
            value: "chore"
      - type: "input"
        title: "Enter the Message"
        key: "Message"
        initialValue: ""
      - type: "confirm"
        title: "Commit"
        body: "{{.Form.Type}}: {{.Form.Message}}"
    command: "git commit -m \"{{.Form.Type}}: {{.Form.Message}}\""
